# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
    ]
