# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='comment',
            new_name='post',
        ),
    ]
