# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default='text of comment'),
            preserve_default=False,
        ),
    ]
